language: node_js
sudo: false
node_js:
  - "iojs"
  - "7"
  - "6"
  - "5"
  - "4"
env:
  - CXX="g++-4.8" CC="gcc-4.8"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
